# syntax=docker/dockerfile@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769
# Partly generated by hassfest.
#
# To update, run python3 -m script.hassfest -p docker
ARG BUILD_FROM
FROM ${BUILD_FROM}
ARG BUILD_ARCH

LABEL \
    io.hass.type="core" \
    org.opencontainers.image.authors="The Home Assistant Authors" \
    org.opencontainers.image.description="Open-source home automation platform running on Python 3" \
    org.opencontainers.image.documentation="https://www.home-assistant.io/docs/" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.title="Home Assistant" \
    org.opencontainers.image.url="https://www.home-assistant.io/"

# Synchronize with homeassistant/core.py:async_stop
ENV \
    S6_SERVICES_GRACETIME=240000 \
    UV_EXTRA_INDEX_URL="https://wheels.home-assistant.io/musllinux-index/" \
    UV_INDEX_STRATEGY=unsafe-best-match \
    UV_SYSTEM_PYTHON=true \
    UV_CACHE_DIR=/root/.cache/uv

WORKDIR /usr/src

# Home Assistant S6-Overlay
COPY rootfs /

# Add go2rtc binary
COPY --from=ghcr.io/alexxit/go2rtc:1.9.14@sha256:675c318b23c06fd862a61d262240c9a63436b4050d177ffc68a32710d9e05bae /usr/local/bin/go2rtc /bin/go2rtc

## Setup Home Assistant Core dependencies
COPY --parents requirements.txt homeassistant/package_constraints.txt homeassistant/
# Verify go2rtc can be executed
RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \
    --mount=type=cache,target=/root/.cache/pip,sharing=locked \
    --mount=type=cache,target=/root/.cache/uv,sharing=locked \
    go2rtc --version \
    && echo "https://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
    && echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
    && apk add --no-cache \
        'ffmpeg>8' \
        openblas \
        openjpeg \
    && apk add --no-cache --virtual .ha-build-deps \
        autoconf \
        automake \
        blas-dev \
        bluez-dev \
        build-base \
        'cargo>1.93' \
        cmake \
        eigen-dev \
        eudev-dev \
        'ffmpeg-dev>8' \
        fftw-dev \
        freetype-dev \
        gfortran \
        git \
        glew-dev \
        glib-dev \
        gmp-dev \
        harfbuzz-dev \
        hdf5-dev \
        lapack-dev \
        libdc1394-dev \
        libffi-dev \
        libjpeg-turbo-dev \
        libpng-dev \
        libtool \
        libtbb-dev \
        libxml2-dev \
        libxslt-dev \
        linux-headers \
        mpc1-dev \
        mpfr-dev \
        nasm \
        openblas-dev \
        openexr-dev \
        openjpeg-dev \
        openssl-dev \
        pkgconf \
        'rust>1.93' \
        tiff-dev \
        uchardet-dev \
        yaml-dev \
        zlib-ng-dev \
    && rustc --version \
    && cargo --version \
    # Install uv at the version pinned in the requirements file
    && pip3 install "uv==$(awk -F'==' '/^uv==/{print $2}' homeassistant/requirements.txt)" \
    && uv pip install \
        -r homeassistant/requirements.txt

COPY requirements_all.txt home_assistant_frontend-* home_assistant_intents-* homeassistant/
RUN --mount=type=cache,target=/root/.cache/uv,sharing=locked \
    if ls homeassistant/home_assistant_*.whl 1> /dev/null 2>&1; then \
        uv pip install homeassistant/home_assistant_*.whl; \
    fi \
    && if [ "${BUILD_ARCH}" = "armhf" ]; then \
        echo "Skipping requirements_all.txt on armhf to stay within GitHub Actions job limits"; \
    else \
        uv pip install \
            -r homeassistant/requirements_all.txt; \
    fi \
    && python3 -c "from pathlib import Path; import re; root = next(Path('/usr/local/lib').glob('python*/site-packages/hass_nabucasa')); [p.write_text(re.sub(r'except ([A-Za-z0-9_.]+(?:, [A-Za-z0-9_.]+)+):', lambda m: f'except ({m.group(1)}):', p.read_text())) for p in root.rglob('*.py')]" \
    && apk del .ha-build-deps

## Setup Home Assistant Core
COPY --parents LICENSE* README* homeassistant/ pyproject.toml homeassistant/
RUN --mount=type=cache,target=/root/.cache/uv,sharing=locked \
    uv pip install \
        -e ./homeassistant \
    && python3 -m compileall \
        homeassistant/homeassistant

WORKDIR /config
